name: Install ArgoCD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-argocd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform/envs/${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::865809098262:role/GitHubRunnerRole

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform apply -auto-approve